services:
  - type: web
    name: chainlit-zomato
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chainlit run app.py --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        sync: false
