services:
  - type: web
    name: generative-ai-project
    runtime: python3
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run main.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
